# Generated by Django 5.1.6 on 2025-03-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('descricao', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
